# Generated by Django 3.1.4 on 2021-11-13 12:00

import django.core.validators
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('caption', models.TextField()),
                ('content', mdeditor.fields.MDTextField()),
                ('finished', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(1)])),
                ('tag_id', models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
