# Generated by Django 3.1.4 on 2021-11-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='caption',
            field=models.TextField(max_length=100),
        ),
    ]
